### PR TITLE
Weather app

### PR DESCRIPTION
**Pull request by enelesmai**
This application uses asynchronous communication with promises or async/await to get data from the OpenWeather API and show it displayed according to what the user required.

It uses: 
* Async
* wait
* JSON
* factory functions
* modules
* webpack to manage bootstrap, fontawesome and images!

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: changes Required❌
# 🙋‍♂️ Selene
#### You have done an amazing job on this one, everything looks almost perfect, the UI is fantastic, but there is a small requirement we have to meet for this project to be approved🤗.
* [x] It uses ES6 syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
- Kindly use an arrow function for this function definition ```function getInfo(search, mode) {```
* [x] Necessary run common commands like `build`, `development` should be in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/))
- Kindly add  ```"dev": "webpack --mode development",``` to your scripts inside package.json, you may include ```"start": "webpack-dev-server --mode development --open"``` as well. This will enable use run the code on our local server.
### That is it kindly make the changes and submit a re-review😎.
#### Happy coding👩‍💻
Addo Forison.

**Comment by enelesmai** [comment]
Thanks for your comments!

I added the ES6 syntax to the getInfo function and the commands to scripts in package.json as requested.

**Review by bellom — APPROVED** [review]
## Hi @enelesmai  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by enelesmai** [comment]
Thanks!

**Pull request merged**
